Fix bug with exception being thrown when data['settings'] is null
When I open a page with Elementor in Wordpress 5.3 I get the following exception:
'''
Fatal error: Uncaught TypeError: Argument 1 passed to Elementor\Controls_Stack::sanitize_settings() must be of the type array, null given, called in /homepages/23/d438281368/htdocs/clickandbuilds/Justponics/wp-content/plugins/elementor/includes/base/controls-stack.php on line 1023 and defined in /homepages/23/d438281368/htdocs/clickandbuilds/Justponics/wp-content/plugins/elementor/includes/base/controls-stack.php:1913 Stack trace: #0 /homepages/23/d438281368/htdocs/clickandbuilds/Justponics/wp-content/plugins/elementor/includes/base/controls-stack.php(1023): Elementor\Controls_Stack->sanitize_settings(NULL) #1 /homepages/23/d438281368/htdocs/clickandbuilds/Justponics/wp-content/plugins/elementor/includes/base/controls-stack.php(1776): Elementor\Controls_Stack->get_data('settings') #2 /homepages/23/d438281368/htdocs/clickandbuilds/Justponics/wp-content/plugins/elementor/core/base/base-object.php(132): Elementor\Controls_Stack->get_init_settings() #3 /homepages/23/d438281368/htdocs/clickandbuilds/Justponics/wp-content/plugi in /homepages/23/d438281368/htdocs/clickandbuilds/Justponics/wp-content/plugins/elementor/includes/base/controls-stack.php on line 1913
Uncaught TypeError: Argument 1 passed to Elementor\Controls_Stack::sanitize_settings() must be of the type array, null given, called in /homepages/23/d438281368/htdocs/clickandbuilds/Justponics/wp-content/plugins/elementor/includes/base/controls-stack.php on line 1023 and defined in /homepages/23/d438281368/htdocs/clickandbuilds/Justponics/wp-content/plugins/elementor/includes/base/controls-stack.php:1913
Stack trace:
#0 /homepages/23/d438281368/htdocs/clickandbuilds/Justponics/wp-content/plugins/elementor/includes/base/controls-stack.php(1023): Elementor\Controls_Stack->sanitize_settings(NULL)
#1 /homepages/23/d438281368/htdocs/clickandbuilds/Justponics/wp-content/plugins/elementor/includes/base/controls-stack.php(1776): Elementor\Controls_Stack->get_data('settings')
#2 /homepages/23/d438281368/htdocs/clickandbuilds/Justponics/wp-content/plugins/elementor/core/base/base-object.php(132): Elementor\Controls_Stack->get_init_settings()
#3 /homepages/23/d438281368/htdocs/clickandbuilds/Justponics/wp-content/plugin
'''

The issue is that sanitize_settings is getting passed a null value when it expects an array.